
var d;d||(d=typeof Module !== 'undefined' ? Module : {});function aa(){return{ga:[],open(a){for(let b=0;b<this.ga.length;b++)if(!(b in this.ga))return this.ga[b]=a,b;this.ga.push(a);return this.ga.length-1},close(a){delete this.ga[a]}}}let ba;document.addEventListener("epoch",function ca(a){ba=a.timeStamp;document.removeEventListener("epoch",ca)});document.dispatchEvent(new Event("epoch"));const da=Date.now(),ea={KeyA:0,KeyZ:1,Quote:2,Slash:3,Space:4},fa=[];
document.addEventListener("keydown",a=>{const b=ea[a.code];void 0!=b&&(fa.push({id:b,time:a.timeStamp-ba}),a.preventDefault())});const l=aa(),n=aa(),ha=window.AudioContext||window.webkitAudioContext;if(!ha)throw"AudioContext API is not supported by your browser";const ia=new ha;var ja=Object.assign({},d),ka=(a,b)=>{throw b;},q="";"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src);q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"";
var r=d.print||console.log.bind(console),t=d.printErr||console.warn.bind(console);Object.assign(d,ja);ja=null;d.quit&&(ka=d.quit);function la(a){u||(u={});u[a]||(u[a]=1,t(a))}var u,v;d.wasmBinary&&(v=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");var ma,x=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function y(a,b){if(a){var c=z,e=a+b;for(b=a;c[b]&&!(b>=e);)++b;if(16<b-a&&c.buffer&&na)a=na.decode(c.subarray(a,b));else{for(e="";a<b;){var f=c[a++];if(f&128){var g=c[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=c[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|c[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a}
function oa(a,b,c){var e=z;if(!(0<c))return 0;var f=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(b>=c)break;e[b++]=h}else{if(2047>=h){if(b+1>=c)break;e[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;e[b++]=224|h>>12}else{if(b+3>=c)break;e[b++]=240|h>>18;e[b++]=128|h>>12&63}e[b++]=128|h>>6&63}e[b++]=128|h&63}}e[b]=0;return b-f}var z,A,pa,qa,ra=[],sa=[],ta=[],ua=[];
function va(){var a=d.preRun.shift();ra.unshift(a)}var B=0,wa=null,C=null;function w(a){if(d.onAbort)d.onAbort(a);a="Aborted("+a+")";t(a);x=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function xa(){return D.startsWith("data:application/octet-stream;base64,")}var D;D="index.wasm";if(!xa()){var ya=D;D=d.locateFile?d.locateFile(ya,q):q+ya}
function za(){var a=D;try{if(a==D&&v)return new Uint8Array(v);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}function Ba(){return v||"function"!=typeof fetch?Promise.resolve().then(function(){return za()}):fetch(D,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+D+"'";return a.arrayBuffer()}).catch(function(){return za()})}
function E(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.Ea;"number"==typeof c?void 0===b.qa?dynCall_v.call(null,c):dynCall_vi.apply(null,[c,b.qa]):c(void 0===b.qa?null:b.qa)}}}function Ca(a){a instanceof Da||"unwind"==a||ka(1,a)}function F(a){if(!x)try{a()}catch(b){Ca(b)}}function Ea(a,b){return setTimeout(function(){F(a)},b)}
function Fa(a,b){Ga=a;Ha=b;if(I)if(Ia||(Ia=!0),0==a)J=function(){var e=Math.max(0,Ja+b-Ka())|0;setTimeout(K,e)};else if(1==a)J=function(){La(K)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",function(e){if("setimmediate"===e.data||"setimmediate"===e.data.target)e.stopPropagation(),c.shift()()},!0);setImmediate=function(e){c.push(e);postMessage("setimmediate","*")}}J=function(){setImmediate(K)}}}var Ka;Ka=()=>performance.now();
function Ma(a,b,c,e,f){!I||w("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");I=a;Na=e;var g=M;Ia=!1;K=function(){if(!x)if(0<Oa.length){var h=Date.now(),k=Oa.shift();k.Ea(k.qa);if(Pa){var m=Pa,p=0==m%1?m-1:Math.floor(m);Pa=k.Ka?p:(8*m+(p+.5))/9}r('main loop blocker "'+k.name+'" took '+(Date.now()-h)+" ms");d.setStatus&&(h=d.statusMessage||"Please wait...",k=
Pa,m=Qa.Ma,k?k<m?d.setStatus(h+" ("+(m-k)+"/"+m+")"):d.setStatus(h):d.setStatus(""));g<M||setTimeout(K,0)}else g<M||(Ra=Ra+1|0,1==Ga&&1<Ha&&0!=Ra%Ha?J():(0==Ga&&(Ja=Ka()),x||d.preMainLoop&&!1===d.preMainLoop()||(F(a),d.postMainLoop&&d.postMainLoop()),g<M||("object"==typeof SDL&&SDL.audio&&SDL.audio.Ha&&SDL.audio.Ha(),J())))};f||(b&&0<b?Fa(0,1E3/b):Fa(1,1),J());if(c)throw"unwind";}var Ia=!1,J=null,M=0,I=null,Na=0,Ga=0,Ha=0,Ra=0,Oa=[];
function Sa(){M++;var a=Ga,b=Ha,c=I;I=null;Ma(c,0,!1,Na,!0);Fa(a,b);J()}var Qa={},Ja,K,Pa,N=!1,Ta=!1,Ua=[];
function Va(){function a(){Ta=document.pointerLockElement===d.canvas||document.mozPointerLockElement===d.canvas||document.webkitPointerLockElement===d.canvas||document.msPointerLockElement===d.canvas}d.preloadPlugins||(d.preloadPlugins=[]);if(!Wa){Wa=!0;try{O=!0}catch(c){O=!1,r("warning: no blob constructor, cannot create blobs with mimetypes")}Xa="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:O?null:r("warning: no BlobBuilder");P="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;d.za||"undefined"!=typeof P||(r("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),d.za=!0);d.preloadPlugins.push({canHandle:function(c){return!d.za&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,e,f,g){var h=null;if(O)try{h=new Blob([c],{type:Ya(e)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Ya(e)}))}catch(p){la("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new Xa,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var k=P.createObjectURL(h),m=new Image;m.onload=()=>{m.complete||w("Image "+e+" could not be decoded");var p=document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,0,0);P.revokeObjectURL(k);f&&f(c)};m.onerror=()=>{r("Image "+k+" could not be decoded");g&&g()};m.src=k}});d.preloadPlugins.push({canHandle:function(c){return!d.Qa&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,e,f,g){function h(){m||(m=!0,f&&f(c))}function k(){m||(m=!0,new Audio,g&&g())}var m=!1;if(O){try{var p=new Blob([c],{type:Ya(e)})}catch(G){return k()}p=P.createObjectURL(p);var H=new Audio;H.addEventListener("canplaythrough",function(){h(H)},!1);H.onerror=function(){if(!m){r("warning: browser could not fully decode audio "+e+", trying slower base64 approach");for(var G="",U=0,L=0,Aa=0;Aa<c.length;Aa++)for(U=U<<8|c[Aa],L+=8;6<=L;){var Ab=U>>L-6&63;L-=6;G+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Ab]}2==
L?(G+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(U&3)<<4],G+="=="):4==L&&(G+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(U&15)<<2],G+="=");H.src="data:audio/x-"+e.substr(-3)+";base64,"+G;h(H)}};H.src=p;Ea(function(){h(H)},1E4)}else return k()}});var b=d.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),d.elementPointerLock&&b.addEventListener("click",function(c){!Ta&&d.canvas.requestPointerLock&&(d.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Za(a,b,c,e){if(b&&d.va&&a==d.canvas)return d.va;var f;if(b){var g={antialias:!1,alpha:!1,ya:1};if(e)for(var h in e)g[h]=e[h];if("undefined"!=typeof $a&&(f=ab(a,g)))var k=bb[f].ua}else k=a.getContext("2d");if(!k)return null;c&&(b||"undefined"==typeof Q||w("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),d.va=k,b&&(cb=bb[f],d.va=Q=cb&&cb.ua),d.Sa=b,Ua.forEach(function(m){m()}),Va());return k}var db=!1,eb=void 0,R=void 0;
function fb(a,b){function c(){N=!1;var g=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(e.exitFullscreen=gb,eb&&e.requestPointerLock(),N=!0,R?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=pa[SDL.screen>>2]|8388608),S(d.canvas),hb()):S(e)):(g.parentNode.insertBefore(e,g),g.parentNode.removeChild(g),R?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=pa[SDL.screen>>2]&-8388609),
S(d.canvas),hb()):S(e));if(d.onFullScreen)d.onFullScreen(N);if(d.onFullscreen)d.onFullscreen(N)}eb=a;R=b;"undefined"==typeof eb&&(eb=!0);"undefined"==typeof R&&(R=!1);var e=d.canvas;db||(db=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=
f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function gb(){if(!N)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var T=0;function La(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===T)T=b+1E3/60;else for(;b+2>=T;)T+=1E3/60;setTimeout(a,Math.max(T-b,0))}}function ib(a){La(function(){F(a)})}
function Ya(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var jb=[];function hb(){var a=d.canvas;jb.forEach(function(b){b(a.width,a.height)})}
function S(a,b,c){b&&c?(a.Ia=b,a.Fa=c):(b=a.Ia,c=a.Fa);var e=b,f=c;d.forcedAspectRatio&&0<d.forcedAspectRatio&&(e/f<d.forcedAspectRatio?e=Math.round(f*d.forcedAspectRatio):f=Math.round(e/d.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*
g)}R?(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(e!=b||f!=c?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var kb={},Wa,O,Xa,P;
function lb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,g){b.drawArraysInstancedANGLE(c,e,f,g)},a.drawElementsInstanced=function(c,e,f,g,h){b.drawElementsInstancedANGLE(c,e,f,g,h)})}
function mb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function nb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}var ob=1,pb=[],V=[],W=[],qb=[],bb=[];function X(a){rb||(rb=a)}
function sb(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}function ab(a,b){a.xa||(a.xa=a.getContext,a.getContext=function(e,f){f=a.xa(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?tb(c,b):0}function tb(a,b){var c=sb(bb),e={Na:c,attributes:b,version:b.ya,ua:a};a.canvas&&(a.canvas.Ja=e);bb[c]=e;("undefined"==typeof b.Da||b.Da)&&ub(e);return c}
function ub(a){a||(a=cb);if(!a.Ga){a.Ga=!0;var b=a.ua;lb(b);mb(b);nb(b);b.La=b.getExtension("EXT_disjoint_timer_query");b.Pa=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var $a={},rb,cb;function vb(a,b,c,e){for(var f=0;f<a;f++){var g=Q[c](),h=g&&sb(e);g?(g.name=h,e[h]=g):X(1282);A[b+4*f>>2]=h}}function wb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function xb(a){var b=Q.Ca;if(b){var c=b.pa[a];"number"==typeof c&&(b.pa[a]=c=Q.getUniformLocation(b,b.Aa[a]+(0<c?"["+c+"]":"")));return c}X(1282)}var yb=[];function zb(a){try{a()}catch(b){w(b)}}var Y=0,Z=null,Bb=[],Cb={},Db={},Eb=0,Fb=null,Gb=[];
function Hb(a){var b={},c;for(c in a)(function(e){var f=a[e];b[e]="function"==typeof f?function(){Bb.push(e);try{return f.apply(null,arguments)}finally{x||(Bb.pop()===e||w(),Z&&1===Y&&0===Bb.length&&(Y=0,zb(d._asyncify_stop_unwind),"undefined"!=typeof Fibers&&Fibers.Ra()))}}:f})(c);return b}function Ib(){var a=Jb(4108),b=a+12;A[a>>2]=b;A[a+4>>2]=b+4096;b=Bb[0];var c=Cb[b];void 0===c&&(c=Eb++,Cb[b]=c,Db[c]=b);A[a+8>>2]=c;return a}
function Kb(a){if(!x)if(0===Y){var b=!1,c=!1;a(()=>{if(!x&&(b=!0,c)){Y=2;zb(()=>d._asyncify_start_rewind(Z));"undefined"!=typeof kb&&I&&Sa();var e=!1;try{var f=(0,d.asm[Db[A[Z+8>>2]]])()}catch(k){f=k,e=!0}var g=!1;if(!Z){var h=Fb;h&&(Fb=null,(e?h.reject:h.resolve)(f),g=!0)}if(e&&!g)throw f;}});c=!0;b||(Y=1,Z=Ib(),zb(()=>d._asyncify_start_unwind(Z)),"undefined"!=typeof kb&&I&&(J=null,M++))}else 2===Y?(Y=0,zb(d._asyncify_stop_rewind),Lb(Z),Z=null,Gb.forEach(e=>F(e))):w("invalid state: "+Y)}
d.requestFullscreen=function(a,b){fb(a,b)};d.requestAnimationFrame=function(a){La(a)};d.setCanvasSize=function(a,b,c){S(d.canvas,a,b);c||hb()};d.pauseMainLoop=function(){J=null;M++};d.resumeMainLoop=function(){Sa()};d.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};d.createContext=function(a,b,c,e){return Za(a,b,c,e)};for(var Q,Mb=new Float32Array(288),Nb=0;288>Nb;++Nb)yb[Nb]=Mb.subarray(0,Nb+1);
var Ob={ba:function(a,b,c){function e(){dynCall_vi.apply(null,[a,b])}0<=c?Ea(e,c):ib(e)},o:function(a,b,c){z.copyWithin(a,b,b+c)},n:function(){return!1},J:function(a,b,c){Ma(function(){dynCall_v.call(null,a)},b,c)},f:function(a){Kb(b=>Ea(b,a))},c:function(){return 0},e:function(a,b){Q.attachShader(V[a],W[b])},Y:function(a,b){Q.bindBuffer(a,pb[b])},_:function(a){Q.bindVertexArray(qb[a])},r:function(a,b,c,e){Q.bufferData(a,c?z.subarray(c,c+b):b,e)},E:function(a){Q.clear(a)},F:function(a,b,c,e){Q.clearColor(a,
b,c,e)},x:function(a){Q.compileShader(W[a])},q:function(){var a=sb(V),b=Q.createProgram();b.name=a;b.ta=b.ra=b.sa=0;b.wa=1;V[a]=b;return a},z:function(a){var b=sb(W);W[b]=Q.createShader(a);return b},R:function(a,b){for(var c=0;c<a;c++){var e=A[b+4*c>>2],f=pb[e];f&&(Q.deleteBuffer(f),f.name=0,pb[e]=null)}},a:function(a){if(a){var b=V[a];b?(Q.deleteProgram(b),b.name=0,V[a]=null):X(1281)}},d:function(a){if(a){var b=W[a];b?(Q.deleteShader(b),W[a]=null):X(1281)}},S:function(a,b){for(var c=0;c<a;c++){var e=
A[b+4*c>>2];Q.deleteVertexArray(qb[e]);qb[e]=null}},p:function(a,b,c){Q.drawArrays(a,b,c)},A:function(a){Q.enable(a)},W:function(a){Q.enableVertexAttribArray(a)},Z:function(a,b){vb(a,b,"createBuffer",pb)},$:function(a,b){vb(a,b,"createVertexArray",qb)},h:function(a,b,c,e){a=Q.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&e?oa(a,e,b):0;c&&(A[c>>2]=b)},i:function(a,b,c){if(c)if(a>=ob)X(1281);else if(a=V[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),A[c>>2]=a.length+
1;else if(35719==b){if(!a.ta)for(b=0;b<Q.getProgramParameter(a,35718);++b)a.ta=Math.max(a.ta,Q.getActiveUniform(a,b).name.length+1);A[c>>2]=a.ta}else if(35722==b){if(!a.ra)for(b=0;b<Q.getProgramParameter(a,35721);++b)a.ra=Math.max(a.ra,Q.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.ra}else if(35381==b){if(!a.sa)for(b=0;b<Q.getProgramParameter(a,35382);++b)a.sa=Math.max(a.sa,Q.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.sa}else A[c>>2]=Q.getProgramParameter(a,b);else X(1281)},v:function(a,
b,c,e){a=Q.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&e?oa(a,e,b):0;c&&(A[c>>2]=b)},w:function(a,b,c){c?35716==b?(a=Q.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(W[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=Q.getShaderParameter(W[a],b):X(1281)},b:function(a,b){b=y(b);if(a=V[a]){var c=a,e=c.pa,f=c.Ba,g;if(!e)for(c.pa=e={},c.Aa={},g=0;g<Q.getProgramParameter(c,35718);++g){var h=Q.getActiveUniform(c,g);var k=h.name;h=h.size;
var m=wb(k);m=0<m?k.slice(0,m):k;var p=c.wa;c.wa+=h;f[m]=[h,p];for(k=0;k<h;++k)e[p]=k,c.Aa[p++]=m}c=a.pa;e=0;f=b;g=wb(b);0<g&&(e=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.Ba[f])&&e<f[0]&&(e+=f[1],c[e]=c[e]||Q.getUniformLocation(a,b)))return e}else X(1281);return-1},j:function(a){a=V[a];Q.linkProgram(a);a.pa=0;a.Ba={}},y:function(a,b,c,e){for(var f="",g=0;g<b;++g){var h=e?A[e+4*g>>2]:-1;f+=y(A[c+4*g>>2],0>h?void 0:h)}Q.shaderSource(W[a],f)},g:function(a,b){Q.uniform1f(xb(a),b)},B:function(a,
b,c,e){Q.uniform3f(xb(a),b,c,e)},t:function(a,b,c,e){if(18>=b){var f=yb[16*b-1],g=qa;e>>=2;for(var h=0;h<16*b;h+=16){var k=e+h;f[h]=g[k];f[h+1]=g[k+1];f[h+2]=g[k+2];f[h+3]=g[k+3];f[h+4]=g[k+4];f[h+5]=g[k+5];f[h+6]=g[k+6];f[h+7]=g[k+7];f[h+8]=g[k+8];f[h+9]=g[k+9];f[h+10]=g[k+10];f[h+11]=g[k+11];f[h+12]=g[k+12];f[h+13]=g[k+13];f[h+14]=g[k+14];f[h+15]=g[k+15]}}else f=qa.subarray(e>>2,e+64*b>>2);Q.uniformMatrix4fv(xb(a),!!c,f)},aa:function(a){a=V[a];Q.useProgram(a);Q.Ca=a},X:function(a,b,c,e,f,g){Q.vertexAttribPointer(a,
b,c,!!e,f,g)},T:function(a,b,c,e){Q.viewport(a,b,c,e)},C:function(a){l.ga[a].track.mediaElement.pause();l.ga[a].track.disconnect();l.close(a)},H:function(a){const b=new Audio(y(a));a=ia.createMediaElementSource(b);a.connect(ia.destination);const c=l.open({ready:!1,track:a,time:0});b.load();b.addEventListener("canplaythrough",()=>l.ga[c].ready=!0);b.addEventListener("timeupdate",()=>l.ga[c].time=1E3*b.currentTime);return c},D:function(a){l.ga[a].track.mediaElement.play()},G:function(a){return l.ga[a].ready},
l:function(a){a=l.ga[a].track.mediaElement.duration;return Infinity===a?-1:1E3*a},k:function(a){return l.ga[a].time},U:function(a,b){const c=d.canvas;d.HEAP32[a>>2]=c.width;d.HEAP32[b>>2]=c.height},m:function(){return Date.now()-da},V:function(a,b){const c=d.canvas;try{return Za(c,!0,!0,{ya:a,Oa:b,antialias:!1})?0:-1}catch(e){return console.error(e),-1}},u:function(a,b,c){a=y(a);b=b?"("+y(b)+") ":"";c=y(c);console[a](b+c)},I:function(a,b){if(!fa.length)return 0;const c=fa.shift();d.HEAPU8[a]=c.id;
d.HEAPU32[b>>2]=c.time;return 1},ca:function(a,b){throw"panic: "+y(a,b);},s:function(a,b){return+y(a,b)},L:function(a){n.close(a)},O:function(a){return!n.ga[a].value},Q:function(a){a=y(a);const b={ready:!1},c=n.open(b);fetch(a).then(e=>e.arrayBuffer()).then(e=>b.value=e).catch(e=>console.error(e)).finally(()=>b.ready=!0);return c},M:function(a,b){a=new Uint8Array(n.ga[a].value);d.HEAPU8.set(a,b)},P:function(a){return n.ga[a].ready},N:function(a){return n.ga[a].value.byteLength},K:function(a,b){const c=
d.canvas;c.width=a;c.height=b}};
(function(){function a(g){g=g.exports;g=Hb(g);d.asm=g;ma=d.asm.da;g=ma.buffer;d.HEAP8=new Int8Array(g);d.HEAP16=new Int16Array(g);d.HEAP32=A=new Int32Array(g);d.HEAPU8=z=new Uint8Array(g);d.HEAPU16=new Uint16Array(g);d.HEAPU32=pa=new Uint32Array(g);d.HEAPF32=qa=new Float32Array(g);d.HEAPF64=new Float64Array(g);sa.unshift(d.asm.ea);B--;d.monitorRunDependencies&&d.monitorRunDependencies(B);0==B&&(null!==wa&&(clearInterval(wa),wa=null),C&&(g=C,C=null,g()))}function b(g){a(g.instance)}function c(g){return Ba().then(function(h){return WebAssembly.instantiate(h,
e)}).then(function(h){return h}).then(g,function(h){t("failed to asynchronously prepare wasm: "+h);w(h)})}var e={a:Ob};B++;d.monitorRunDependencies&&d.monitorRunDependencies(B);if(d.instantiateWasm)try{var f=d.instantiateWasm(e,a);return f=Hb(f)}catch(g){return t("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return v||"function"!=typeof WebAssembly.instantiateStreaming||xa()||"function"!=typeof fetch?c(b):fetch(D,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,
e).then(b,function(h){t("wasm streaming compile failed: "+h);t("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.ea).apply(null,arguments)};d._main=function(){return(d._main=d.asm.fa).apply(null,arguments)};
var Jb=d._malloc=function(){return(Jb=d._malloc=d.asm.ha).apply(null,arguments)},Lb=d._free=function(){return(Lb=d._free=d.asm.ia).apply(null,arguments)},dynCall_vi=d.dynCall_vi=function(){return(dynCall_vi=d.dynCall_vi=d.asm.ja).apply(null,arguments)},dynCall_v=d.dynCall_v=function(){return(dynCall_v=d.dynCall_v=d.asm.ka).apply(null,arguments)};d._asyncify_start_unwind=function(){return(d._asyncify_start_unwind=d.asm.la).apply(null,arguments)};
d._asyncify_stop_unwind=function(){return(d._asyncify_stop_unwind=d.asm.ma).apply(null,arguments)};d._asyncify_start_rewind=function(){return(d._asyncify_start_rewind=d.asm.na).apply(null,arguments)};d._asyncify_stop_rewind=function(){return(d._asyncify_stop_rewind=d.asm.oa).apply(null,arguments)};var Pb;function Da(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}C=function Qb(){Pb||Rb();Pb||(C=Qb)};
function Rb(){function a(){if(!Pb&&(Pb=!0,d.calledRun=!0,!x)){E(sa);E(ta);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Sb){var b=d._main;try{var c=b(0,0);if(!noExitRuntime){if(d.onExit)d.onExit(c);x=!0}ka(c,new Da(c))}catch(e){Ca(e)}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)b=d.postRun.shift(),ua.unshift(b);E(ua)}}if(!(0<B)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)va();E(ra);0<B||(d.setStatus?
(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=Rb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Sb=!0;d.noInitialRun&&(Sb=!1);Rb();
